### ISSUE TITLE
Bug in the form validation

### ISSUE THREAD

**Issue by IuriiRR** [softmasterlab/univer#3]
В последнем коммите есть баг с проверкой всех полей на валидность. Так как проверкой занимается одна переменная (let valid). 

Steps to reproduce:
Если очередность заполнения полей выпадет так, что последнее поле будет заполнено корректно - любая форма будет принята в работу не смотря на нарушения.

Где найти:
112 (строка) if (valid == true) {
univer/static/js/reg.js 

Проверено на коммите e2b3f222d37400645b9be14b1f4590a25fcfa0c9

**Comment by softmasterlab** [comment]
Принимаются предложения по исправлению (конкурс исходников)

**Comment by softmasterlab** [comment]
Подсказка:
Можно создать список логических значений для проверки каждого поля по-отдельности
